<?php

namespace Container8nyNub7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\JobController' shared autowired service.
     *
     * @return \App\Controller\JobController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\JobController'] = $instance = new \App\Controller\JobController(new \App\Service\JobOfferService(new \App\Service\AuthUtilsService(), $container->getEnv('JOJIBA_API_CLIENT_ID'), $container->getEnv('JOJIBA_API_CLIENT_SECRET')));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'twig' => '?',
        ]))->withContext('App\\Controller\\JobController', $container));

        return $instance;
    }
}
