<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8nyNub7\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8nyNub7/App_KernelDevContainer.php') {
    touch(__DIR__.'/Container8nyNub7.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\Container8nyNub7\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \Container8nyNub7\App_KernelDevContainer([
    'container.build_hash' => '8nyNub7',
    'container.build_id' => 'd5c2c797',
    'container.build_time' => 1691329756,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8nyNub7');
